import { GetState, SetState } from 'zustand'
import { MyState } from './useStore'

export interface TableTennisStore {
  tableTennisEvents: unknown;
}

const createTableTennisStore = (set: SetState<MyState>, get: GetState<MyState>): TableTennisStore => ({
  tableTennisEvents: [{ 'city': 'Special Admin Region', 'competitions': [{ 'competitionId': 35, 'drawSize': 32, 'externalId': '5365-TTEMSINGLES', 'organisation': 'WTT', 'participantType': 'MS', 'qualifyingDrawSize': 0 }], 'countryCode': 'CHN', 'endDate': '2021-12-13', 'eventsSummary': { '2021-07-13': { 'MS': 31 } }, 'identifier': 16, 'location': 'Tap Seac Multisport Complex', 'numberOfMatches': 31, 'startDate': '2021-04-06', 'status': 'Confirmed', 'tournamentName': 'WTT China Champions 2021 - IMGSIM 2', 'utcOffset': 0, 'year': 2021 }, { 'city': 'Olomouc', 'competitions': [{ 'competitionId': 41, 'drawSize': 32, 'externalId': '2480-TTEMSINGLES', 'organisation': 'ITTF', 'participantType': 'MS', 'qualifyingDrawSize': 4 }, { 'competitionId': 42, 'drawSize': 32, 'externalId': '2480-TTEWSINGLES', 'organisation': 'ITTF', 'participantType': 'LS', 'qualifyingDrawSize': 4 }, { 'competitionId': 43, 'drawSize': 16, 'externalId': '2480-TTEMDOUBLES', 'organisation': 'ITTF', 'participantType': 'MD', 'qualifyingDrawSize': 16 }, { 'competitionId': 44, 'drawSize': 16, 'externalId': '2480-TTEXDOUBLES', 'organisation': 'ITTF', 'participantType': 'XD', 'qualifyingDrawSize': 16 }, { 'competitionId': 45, 'drawSize': 16, 'externalId': '2480-TTEWDOUBLES', 'organisation': 'ITTF', 'participantType': 'LD', 'qualifyingDrawSize': 32 }], 'countryCode': 'CZE', 'endDate': '2021-08-25', 'eventsSummary': { '2021-08-24': { 'LD': 6, 'MD': 6, 'LS': 12, 'XD': 7, 'MS': 12 }, '2021-08-23': { 'LD': 8, 'MD': 8, 'LS': 16, 'XD': 8, 'MS': 16 }, '2021-08-22': { 'QLS': 2, 'QXD': 2, 'QLD': 8, 'QMD': 7, 'MS': 19, 'LS': 38, 'QMS': 2 }, '2021-08-21': { 'QXD': 6, 'QLD': 2, 'LS': 19, 'MS': 38 }, '2021-08-25': { 'LD': 1, 'MD': 1, 'LS': 3, 'MS': 3 } }, 'identifier': 18, 'location': 'OMEGA Sport Center', 'numberOfMatches': 265, 'startDate': '2021-08-21', 'status': 'Confirmed', 'tournamentName': '2021 ITTF Czech International Open', 'utcOffset': 0, 'year': 2021 }, { 'city': 'Special Admin Region', 'competitions': [], 'countryCode': 'CHN', 'endDate': '2021-12-13', 'eventsSummary': {}, 'identifier': 12, 'location': 'Tap Seac Multisport Complex', 'numberOfMatches': 0, 'startDate': '2021-04-06', 'status': 'Confirmed', 'tournamentName': 'OLD WTT China Champions 2021 - IMGSIM 2', 'utcOffset': 0, 'year': 2021 }],
})

export default createTableTennisStore
